# permissions for end users to edit fluentbitconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbitconfiguration-editor-role
rules:
- apiGroups:
  - config.tmax.io
  resources:
  - fluentbitconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.tmax.io
  resources:
  - fluentbitconfigurations/status
  verbs:
  - get
