// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterPlugin) DeepCopyInto(out *FilterPlugin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterPlugin.
func (in *FilterPlugin) DeepCopy() *FilterPlugin {
	if in == nil {
		return nil
	}
	out := new(FilterPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentBitConfiguration) DeepCopyInto(out *FluentBitConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentBitConfiguration.
func (in *FluentBitConfiguration) DeepCopy() *FluentBitConfiguration {
	if in == nil {
		return nil
	}
	out := new(FluentBitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FluentBitConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentBitConfigurationList) DeepCopyInto(out *FluentBitConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FluentBitConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentBitConfigurationList.
func (in *FluentBitConfigurationList) DeepCopy() *FluentBitConfigurationList {
	if in == nil {
		return nil
	}
	out := new(FluentBitConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FluentBitConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentBitConfigurationSpec) DeepCopyInto(out *FluentBitConfigurationSpec) {
	*out = *in
	if in.InputPlugins != nil {
		in, out := &in.InputPlugins, &out.InputPlugins
		*out = make([]InputPlugin, len(*in))
		copy(*out, *in)
	}
	if in.FilterPlugins != nil {
		in, out := &in.FilterPlugins, &out.FilterPlugins
		*out = make([]FilterPlugin, len(*in))
		copy(*out, *in)
	}
	if in.OutputPlugins != nil {
		in, out := &in.OutputPlugins, &out.OutputPlugins
		*out = make([]OutputPlugin, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentBitConfigurationSpec.
func (in *FluentBitConfigurationSpec) DeepCopy() *FluentBitConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(FluentBitConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentBitConfigurationStatus) DeepCopyInto(out *FluentBitConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentBitConfigurationStatus.
func (in *FluentBitConfigurationStatus) DeepCopy() *FluentBitConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(FluentBitConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputPlugin) DeepCopyInto(out *InputPlugin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputPlugin.
func (in *InputPlugin) DeepCopy() *InputPlugin {
	if in == nil {
		return nil
	}
	out := new(InputPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputPlugin) DeepCopyInto(out *OutputPlugin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputPlugin.
func (in *OutputPlugin) DeepCopy() *OutputPlugin {
	if in == nil {
		return nil
	}
	out := new(OutputPlugin)
	in.DeepCopyInto(out)
	return out
}
